---

# Install Packages
- name: Install Software packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:  "{{ software_packages }}"

# Configure Timezone
- name: Link /etc/localtime to /usr/share/zoneinfo/{{ timezone }}
  file:
    state: link
    path: "/etc/localtime"
    src: "/usr/share/zoneinfo/{{ timezone }}"
    force: yes
    owner: root
    group: root

- name: Set the timezone using timedatectl
  command: "/usr/bin/timedatectl set-timezone {{ timezone }}"

# Configure Locale
# Install an appropriate /etc/locale.gen
- name: Add the {{ host_locale }} locale
  lineinfile:
    path: /etc/locale.gen
    regexp: "{{ host_locale }}"
    line: "{{ host_locale }}"
    state: present

# run locale-gen
- name: Generate the appropriate locales
  command: /usr/sbin/locale-gen

# Make the configuration directory
- name: Create the xorg.conf.d directory
  file:
    state: directory
    path: /etc/X11/xorg.conf.d/
    force: yes
    owner: root
    group: root
    mode: 0755

# Download the keyboard configuration file
- name: Fetch the keyboard configuration for the PocketChip
  get_url:
    url: https://raw.githubusercontent.com/NextThingCo/pocketchip-configs/a524554d0c2b8715f4b7131e68055b645dcb140b/pocketchip-configs/X11/xkb/symbols/pocketchip
    dest: /usr/share/X11/xkb/symbols/pocketchip
    owner: root
    group: root
    mode: 0644

# Configure Keyboard 
- name: Install the PocketKeyboard configuration file
  copy:
    src: pocketchip.conf
    dest: /etc/X11/xorg.conf.d/
    owner: root
    group: root
    mode: 0644

# Install Touchscreen Calibration script
- name: Install the Touchscreen Calibration script
  copy:
    src: calibratescreen.sh
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755

- debug: 
    msg: "You will be able to calibrate your touchscreen by just running 'sudo /usr/local/bin/calibratescreen.sh'"

